
package celulares.GUI;
import java.sql.*;
import javax.swing.JOptionPane;
import com.itextpdf.text.Document;
import celulares.BL.celularesBL;
import celulares.DAL.conexion;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;



public class celulares extends javax.swing.JFrame {

    DefaultTableModel modelo;
    
    public celulares() {
        initComponents();
        
        String[] titulo= {"ID","Nombre","Perfil","Producto","Fecha","Detalles"};
        
        modelo= new DefaultTableModel(null, titulo);
        clientesTable.setModel(modelo);
        
        mostrarDatos();
        
        agregarButton.setEnabled(true);
        editarButton.setEnabled(false);
        eliminarButton.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoLabel = new javax.swing.JLabel();
        tituloLabel = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        nombreLabel = new javax.swing.JLabel();
        nombreField = new javax.swing.JTextField();
        perfilLabel = new javax.swing.JLabel();
        perfilField = new javax.swing.JTextField();
        productoLabel = new javax.swing.JLabel();
        productoField = new javax.swing.JTextField();
        detallesLabel = new javax.swing.JLabel();
        agregarButton = new javax.swing.JButton();
        eliminarButton = new javax.swing.JButton();
        fechaLabel = new javax.swing.JLabel();
        fechaField = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        clientesTable = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        detallesArea = new javax.swing.JTextArea();
        editarButton = new javax.swing.JButton();
        limpiarButton = new javax.swing.JButton();
        pdfButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/celulares/recursos/logo.png"))); // NOI18N

        tituloLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/celulares/recursos/portada.jpg"))); // NOI18N

        idLabel.setText("ID:");

        idField.setEditable(false);
        idField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idFieldActionPerformed(evt);
            }
        });

        nombreLabel.setText("Nombre:");

        perfilLabel.setText("Celular:");

        productoLabel.setText("Producto:");

        detallesLabel.setText("Detalles:");

        agregarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/celulares/recursos/agregar-archivo.png"))); // NOI18N
        agregarButton.setText("Agregar");
        agregarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarButtonActionPerformed(evt);
            }
        });

        eliminarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/celulares/recursos/eliminar.png"))); // NOI18N
        eliminarButton.setText("Eliminar");
        eliminarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarButtonActionPerformed(evt);
            }
        });

        fechaLabel.setText("Fecha:");

        clientesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        clientesTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientesTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(clientesTable);

        detallesArea.setColumns(20);
        detallesArea.setRows(5);
        jScrollPane5.setViewportView(detallesArea);

        editarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/celulares/recursos/editar.png"))); // NOI18N
        editarButton.setText("Editar");
        editarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarButtonActionPerformed(evt);
            }
        });

        limpiarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/celulares/recursos/boton-x.png"))); // NOI18N
        limpiarButton.setText("Cancelar");
        limpiarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarButtonActionPerformed(evt);
            }
        });

        pdfButton.setText("Crear PDF");
        pdfButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdfButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(logoLabel)
                        .addGap(48, 48, 48)
                        .addComponent(tituloLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(detallesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(productoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(productoField))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(perfilLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(perfilField))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nombreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nombreField))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idField))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(agregarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(editarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pdfButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fechaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fechaField))
                            .addComponent(jScrollPane5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(eliminarButton)
                                .addGap(18, 18, 18)
                                .addComponent(limpiarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tituloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eliminarButton)
                            .addComponent(limpiarButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nombreLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nombreField, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(perfilLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(perfilField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(productoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(productoField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fechaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(fechaField)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(detallesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pdfButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(agregarButton, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                .addComponent(editarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarButtonActionPerformed
        conexion objConexion= new conexion();
        
        celularesBL oClientes= recuperarDatosGUI();
        
        String strSentenciaInsert= String.format("INSERT INTO clientes (ID,Nombre,Perfil,Producto,Fecha,Detalles)VALUES(null,'%s','%s','%s','%s','%s')",oClientes.getNombre(),oClientes.getPerfil(),oClientes.getProducto(),oClientes.getFecha(),oClientes.getDetalles());
        
        
        objConexion.ejecutarSentenciaSQL(strSentenciaInsert);
        
        this.mostrarDatos();
        
        agregarButton.setEnabled(false);
        editarButton.setEnabled(true);
        eliminarButton.setEnabled(true);
        
        
    }//GEN-LAST:event_agregarButtonActionPerformed

    private void clientesTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientesTableMouseClicked
        
        if(evt.getClickCount()==1){
        
            JTable receptor= (JTable)evt.getSource();
            
            idField.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 0).toString());
            nombreField.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 1).toString());
            perfilField.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 2).toString());
            productoField.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 3).toString());
            fechaField.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 4).toString());
            detallesArea.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 5).toString());
            
            agregarButton.setEnabled(false);
            editarButton.setEnabled(true);
            eliminarButton.setEnabled(true);
        
        }
        
    }//GEN-LAST:event_clientesTableMouseClicked

    private void eliminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarButtonActionPerformed
        
        conexion objConexion= new conexion();
        
        celularesBL oClientes= recuperarDatosGUI();
        
        String strSentenciaInsert= String.format("DELETE FROM clientes WHERE ID= %d",oClientes.getId());
        
        
        objConexion.ejecutarSentenciaSQL(strSentenciaInsert);
        this.mostrarDatos();
        
    }//GEN-LAST:event_eliminarButtonActionPerformed

    private void editarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarButtonActionPerformed
        conexion objConexion= new conexion();
        
        celularesBL oClientes= recuperarDatosGUI();
        
        String strSentenciaInsert= String.format("UPDATE clientes SET Nombre= '%s',Perfil='%s',Producto='%s',Fecha='%s',Detalles='%s' WHERE ID= %d",oClientes.getNombre(),oClientes.getPerfil(),oClientes.getProducto(),oClientes.getFecha(),oClientes.getDetalles(),oClientes.getId());
        
        
        objConexion.ejecutarSentenciaSQL(strSentenciaInsert);
        
        this.mostrarDatos();
    }//GEN-LAST:event_editarButtonActionPerformed

    private void limpiarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarButtonActionPerformed
        idField.setText("");
        nombreField.setText("");
        perfilField.setText("");
        productoField.setText("");
        fechaField.setText("");
        detallesArea.setText("");
        
        agregarButton.setEnabled(true);
        editarButton.setEnabled(false);
        eliminarButton.setEnabled(false);
        
    }//GEN-LAST:event_limpiarButtonActionPerformed

    private void idFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idFieldActionPerformed

    private void pdfButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdfButtonActionPerformed
      
        Document documento= new Document();
        
        try{
            String ruta= System.getProperty("user.home");
            PdfWriter.getInstance(documento,new FileOutputStream(ruta+"/Desktop/Reporte de clientes.pdf"));
            
            Image logo= Image.getInstance("img/logo.png");
            logo.scaleToFit(100,150);
            logo.setAlignment(Chunk.ALIGN_CENTER);
            
            Paragraph parrafo= new Paragraph();
            parrafo.setAlignment(Paragraph.ALIGN_CENTER);
            parrafo.add("THE SOFT PARADE Tecnology® \n\n");
            parrafo.setFont(FontFactory.getFont("Tahoma",18,Font.BOLD,BaseColor.MAGENTA));
            parrafo.add("Clientes \n\n");
            
            
            documento.open();
            documento.add(logo);
            documento.add(parrafo);
            
            PdfPTable tabla= new PdfPTable(6);
            tabla.addCell("ID");
            tabla.addCell("Nombre");
            tabla.addCell("Perfil");
            tabla.addCell("Producto");
            tabla.addCell("Fecha");
            tabla.addCell("Detalles");
            
            try{
            
                Connection c= DriverManager.getConnection("jdbc:sqlite:bd/Clientes.s3db","root","");
                PreparedStatement pst= c.prepareStatement("select * from clientes");
                
                ResultSet rs= pst.executeQuery();
                
                if(rs.next()){
                    
                    do{
                        tabla.addCell(rs.getString(1));
                        tabla.addCell(rs.getString(2));
                        tabla.addCell(rs.getString(3));
                        tabla.addCell(rs.getString(4));
                        tabla.addCell(rs.getString(5));
                        tabla.addCell(rs.getString(6));
                    }while(rs.next());
                    
                    documento.add(tabla);
                }
                
            }catch(DocumentException | SQLException e){
            
            }
        
        }catch(DocumentException | FileNotFoundException e){
        
        
        }catch(IOException e){
            System.out.println("Error en la imagen"+e);
        }
        
        documento.close();
        JOptionPane.showMessageDialog(null, "Reporte creado");
     
    }//GEN-LAST:event_pdfButtonActionPerformed
    public celularesBL recuperarDatosGUI(){
    
        celularesBL oClientes= new celularesBL();
        
        int ID= (idField.getText().isEmpty())?0: Integer.parseInt(idField.getText());
        
        oClientes.setId(ID);
        oClientes.setNombre(nombreField.getText());
        oClientes.setPerfil(perfilField.getText());
        oClientes.setProducto(productoField.getText());
        oClientes.setFecha(fechaField.getText());
        oClientes.setDetalles(detallesArea.getText());
        
        return oClientes;
    
    }
    
    public void mostrarDatos(){
        
        while(modelo.getRowCount()>0){
        
            modelo.removeRow(0);
        
        }
    
        conexion objConexion= new conexion();
         try{
        
            ResultSet resultado= objConexion.consultarRegistros("SELECT * FROM clientes");
            while(resultado.next()){
            
                System.out.println(resultado.getString("ID"));
                System.out.println(resultado.getString("Nombre"));
                System.out.println(resultado.getString("Perfil"));
                System.out.println(resultado.getString("Producto"));
                System.out.println(resultado.getString("Fecha"));
                System.out.println(resultado.getString("Detalles"));
                
                Object[] oUsuario= {resultado.getString("ID"),resultado.getString("Nombre"),resultado.getString("Perfil"),resultado.getString("Producto"),resultado.getString("Fecha"),resultado.getString("Detalles")};
            
                modelo.addRow(oUsuario);
            }
            
        }catch(Exception e){
        
            System.out.println(e);
        
        }
    
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(celulares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(celulares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(celulares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(celulares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new celulares().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarButton;
    private javax.swing.JTable clientesTable;
    private javax.swing.JTextArea detallesArea;
    private javax.swing.JLabel detallesLabel;
    private javax.swing.JButton editarButton;
    private javax.swing.JButton eliminarButton;
    private javax.swing.JTextField fechaField;
    private javax.swing.JLabel fechaLabel;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel idLabel;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton limpiarButton;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JTextField nombreField;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JButton pdfButton;
    private javax.swing.JTextField perfilField;
    private javax.swing.JLabel perfilLabel;
    private javax.swing.JTextField productoField;
    private javax.swing.JLabel productoLabel;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables
}
